# QUERY 1: CALCULATING ANNUAL REVENUE
  create view Annual_revenue as
  select year(Order_date),sum(case when Is_cancelled=1 then Amount=0 else Amount end)
  from Orders
  group by YEAR(Order_date) 
  order by YEAR(Order_date) 
   ;

# QUERY 2: CALCULATING MONTHLY REVENUE REPORTS: 
  create view Monthly_revenue as
  select MONTH(Order_date),sum(case when Is_cancelled=1 then Amount=0 else Amount end)
  from Orders
  group by MONTH(Order_date) 
  order by MONTH(Order_date) 
   ;

# QUERY 3: CALCULATING REVENUE GENERATED FORM EACH CUSTOMER
  create view Customer_based_revenue as
  select Customers.Customer_id,email,sum(case when Is_cancelled=1 then Amount=0 else Amount end)
  from Customers
  left join Orders on 
  Customers.Customer_id=Orders.Customer_id
  group by Customer_id
  Order by Customer_id
  ;
# QUERY 4: CALCULATING REVENUE GENERATED BY EACH PRODUCT
   create view Product_based_revenue as
   select Products.Product_id,Product_name,Sum(case when Is_cancelled=1 then Amount=0 else Amount end)
   from Products
   left join Orders on
   Products.Product_id=Orders.Product_id
   group by Product_id
   Order by Product_id
   ;
  
# QUERY 5: CALCULATING REVENUE FROM DISCOUNT MONTHS OVER THE YEARS   
     create view Discount_based_revenue as
	 select YEAR(Order_date),sum(case when Is_cancelled=1 then Amount=0 else Amount end)
	 from Orders
     where MONTH(Order_date) in (11,12)
	 group by YEAR(Order_date) 
	 Order by YEAR(Order_date)
	   ; 

# QUERY 6: CALCULATE TOTAL REVENUE G   
   